### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by ghost** [AAADevs/alpha-bot#20]
### About
This feature of the bot has all the games the users can play, see the membercount, see covid related information, setting reminders and listening to music

### Reference Link
https://github.com/Jackojc/cobot-19 (for COVID commands)
https://github.com/python-discord/seasonalbot (for games users can play)
https://github.com/jagrosh/MusicBot (for music plugin)

### Commands Needed
![image](https://user-images.githubusercontent.com/66989464/89398343-9a92c980-d72e-11ea-8e10-914b168913bf.png)

### Examples for games
![image](https://user-images.githubusercontent.com/66989464/89399063-8f8c6900-d72f-11ea-95bd-ac1f7b1c2911.png)
![image](https://user-images.githubusercontent.com/66989464/89399140-af239180-d72f-11ea-85c0-d0749feeeae1.png)
![image](https://user-images.githubusercontent.com/66989464/89399156-b64a9f80-d72f-11ea-83ce-5eff02b91bbb.png)
![image](https://user-images.githubusercontent.com/66989464/89399422-17727300-d730-11ea-8c61-f6178a38d795.png)
![image](https://user-images.githubusercontent.com/66989464/89399487-2ce79d00-d730-11ea-855d-556912fad14f.png)

**Comment by DataPirate007** [comment]
I have made the snakes and ladders, minesweeper, Battleship, TriviaQuiz code. I just got them from the seasonal bot and edited the paths and code at some places. Once they are placed into this repo the paths would again need to be changed

**Comment by solidassassin** [comment]
Don't list multiple enhancements in one pull request. It's messy and confusing.
